### ISSUE TITLE
Please add a TypeScript declaration file

### ISSUE THREAD

**Issue by Michael55555** [Vheissu/steem-stream#1]
I love using this package,
but I think that it would be much easier with, clear documentation and typescript declarations for all parameters and functions.
It would save a lot more time and headache.

**Comment by Vheissu** [comment]
@Michael55555 Cheers dude. It's definitely on the list to make it more TypeScript friendly for developers. I might be able to knock something together this week.

**Comment by Michael55555** [comment]
Thank you very much, I'm looking forward to work with it!

**Comment by Vheissu** [comment]
@Michael55555 I took the extreme approach and rewrote the module in TypeScript itself. As a result, there are definitions now. I'll focus on making them more useful and strongly typed in subsequent releases, but this will remove any module warnings from having no typings.
